name: Organization Metrics
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate organization metrics
        uses: lowlighter/metrics@latest
        with:
          filename: intro.svg
          token: ${{ secrets.METRICS_TOKEN_ORG }}
          user: Private-Bots-Official
          base: header, activity, repositories
          template: classic
          plugin_introduction: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          config_timezone: Asia/Calcutta
          plugin_traffic: yes
