name: Organization Metrics
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate organization metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN_ORG }}
          user: Private-Bots-Official
          base: header
          template: classic
          output: README.md
          plugin_organizations: yes
          plugin_organizations_limit: 10
          plugin_organizations_sections: members,repositories
          plugin_repositories: yes
          plugin_repositories_description: yes
          plugin_repositories_forks: yes
          plugin_repositories_languages: yes
          plugin_members: yes
          plugin_members_limit: 24
          plugin_stars: yes
          plugin_people: yes
          plugin_activity: yes

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "📈 Update organization metrics"
          git push
